### ISSUE TITLE
cursor on nav > Dev is wrong

### ISSUE THREAD

**Issue by denjello** [PieceMeta/piecemeta-angular-frontend#1]
This is common to angular bootstrap and really just a cosmetic fix for the UI, because the functionality is fine.

Simple css fix for mouse cursor showing the text cursor instead of the pointer.

`nav li.dropdown { cursor: pointer; }`

**Comment by denjello** [comment]
The [docs here](https://angular-ui.github.io/bootstrap/) actually suggest:
`.nav, .pagination, .carousel, .panel-title a { cursor: pointer; }`

**Comment by dasantonym** [comment]
thanks, included that!
