### ISSUE TITLE
osc player stops emitting data

### ISSUE THREAD

**Issue by dasantonym** [PieceMeta/piecemeta-angular-frontend#11]
circumstances are not 100% clear yet, but i have seen it, too now

**Comment by dasantonym** [comment]
this seems to be related to packages having streams of different lengths. i'm just not sure why it stops entirely instead of just sending the remaining accessible data.

still a good thing it's not the transport itself. this shouldn't be too hard to fix.

**Comment by dasantonym** [comment]
ok, so i am now at a point where it just works on my machine. as well from the vm as my local api instance.

fjennet, when you get around to updating the vm and downloading this updated build, please drop me a line if you're still experiencing these problems. thanks!

https://drive.google.com/file/d/0B7mSRDyDXir7ekVwaXpqOUFNc00/view?usp=sharing

**Comment by fjenett** [comment]
… checking

**Comment by fjenett** [comment]
Seems to work fine at the moment.
