### ISSUE TITLE
General performance improvements

### ISSUE THREAD

**Issue by denjello** [PieceMeta/piecemeta-angular-frontend#25]
There are several other issues in the tracker regarding system / interface performance. I would classify them in two camps, and they are V8 optimization and angular optimization. 
## VM

One important fix for V8 optimization is the removal of `try...catch`. The VM cannot optimize such loops.

```
// status quo
    try {
        input = JSON.parse(fileData); // will not optimize
        cb(null, input);  // will not optimize
    } catch (e) {
        cb(new Error('error parsing json: ' + e.toString()), null);
    }


// although the following has more code, 
// it can be optimized by the VM
var errorObject = {value: null}; // will be optimized
function tryCatch(fn, ctx, args) { // will be optimized
    try {
        return fn.apply(ctx, args);
    }
    catch(e) {
        errorObject.value = e;
        return errorObject;
    }
}

function parseFileData(fileData) { // will be optimized
    input = JSON.parse(fileData);
    return input;
}

var result = tryCatch(parseFileData_sensitive, void 0, fileData); // will be optimized
//Unambiguously tells whether the call threw
if(result === errorObject) { // will be optimized
    var error = errorObject.value;
    cb(new Error('error parsing json: ' + error.toString()), null);
} else { // will be optimized
    cb(null, result);
}
```

It is also worth mentioning that in high-performance JS like **piecemeta**, `for-in` can be really, really confusing for the VM and is also not likely to be optimized. As there are quite a few cases of the for-in construct here in the codebase, I would highly recommend having a quick look at this:

https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#5-for-in

Anyway, here is the list of constructs that will not be optimized by the VM at runtime (according to petkaantonov:

Currently not optimizable:
-   Generator functions
-   Functions that contain a for-of statement
-   Functions that contain a try-catch statement
-    Functions that contain a try-finally statement
-    Functions that contain a compound let assignment
-    Functions that contain a compound const assignment
-    Functions that contain object literals that contain **proto**, or get or set declarations.

Likely never optimizable:
-    Functions that contain a debugger statement
-    Functions that call literally eval()
-    Functions that contain a with statement
## ANGULAR

With angular, it is important to keep tabs on what the client knows as well as what it shows. These are two very different worlds. For example, if you have 240 tracks, there is NO POSSIBLE WAY to see them all on a laptop screen. So why would they be graphically rendered? That part of the DOM does not need to be repainted, thus freeing up resources for the rest of the system. This is why I prefer to let the client know everything it needs, but only show it what it has requested to see. Especially when the client is viewing lots of dynamic data, even though Angular uses requestAnimationFrame, the client will be repainting ALL the time and consuming resources. Even offscreen elements that are visible are repainted. :( 

Another easy angular 1.3+ fix you can use is **one-time binding** to reduce lookups in the $scope after initialization. this is a minimal fix to enhance the speed of the app, of course the binding is forgotten after initialization...

something like: 

```
.row.bottom-space
    .col-sm-12
        h3 {{ ::data.dataPackage.title }}
```

Here are a couple of resources for your reading pleasure:

http://bahmutov.calepin.co/improving-angular-web-app-performance-example.html
http://tech.small-improvements.com/2013/09/10/angularjs-performance-with-large-lists/
http://www.html5rocks.com/en/tutorials/speed/v8/

**Comment by dasantonym** [comment]
thanks! i started adding one-way bindings where appropriate and will continue to do so. i'll also check the 1k+ occurrences of for..in loops. argh.

**Comment by dasantonym** [comment]
fyi, i'm now transitioning from async to bluebird promises so i can catch those errors and it seems to have almost double the performance compared to waterfalls. i'll be using these for the ito modules as well.

https://github.com/petkaantonov/bluebird/tree/master/benchmark
