### ISSUE TITLE
edit package page does not show newly added channel after import

### ISSUE THREAD

**Issue by fjenett** [PieceMeta/piecemeta-angular-frontend#7]
On package / edit:
- import channel
- (all that is needed to import) … click "add channel"
- back at packages after save the new channel is missing from the list at the bottom

**Comment by dasantonym** [comment]
that sounds like you're not on the most recent version of the api. the memcache integration is buggy and now bypassed. can you run update-all on the vm again?

**Comment by fjenett** [comment]
Jup. Seems gone now, tx
