### ISSUE TITLE
edit package page sort channels

### ISSUE THREAD

**Issue by fjenett** [PieceMeta/piecemeta-angular-frontend#8]
On the edit package page the channels that are created could be sorted by title … or there could be a way to sort these.

**Comment by fjenett** [comment]
… same for menu on the add channels page.

(or i need to get used to the sort by latest at top …)

**Comment by fjenett** [comment]
… actually does not seem sorted at all at the moment

**Comment by dasantonym** [comment]
yeah, the "sorting" is the db shitting out records at will. i'll get on that next and add a search box as well.

**Comment by dasantonym** [comment]
sorting is now done by title, more advanced stuff here: https://github.com/PieceMeta/piecemeta-angular-frontend/issues/16
